/// Flutter icons SocialNetworkIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialNetworkIcons
///      fonts:
///       - asset: fonts/SocialNetworkIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SocialNetworkIcons {
  SocialNetworkIcons._();

  static const _kFontFam = 'SocialNetworkIcons';

  static const IconData vkontakte = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe803, fontFamily: _kFontFam);
}
